services:
  redpanda:
    image: redpandadata/redpanda:v23.3.14
    command:
      - redpanda start  # 브로커 실행
      - --overprovisioned # 로컬용
      - --smp=1 # 1Cpu
      - --memory=1G # 1G mem
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092 # 브로커 리슨 포트 9092, host는 19092로 리슨
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092 # 컨테이너 내부에서 접근할 때 주소, 외부에서 접근할 때 주소
    ports:
      - "9092:9092"     
      - "19092:19092"   
      - "9644:9644"     
  kafka-ui:   # kafka UI 서비스 
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"     # 웹 UI: http://localhost:8081
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:9092  # ui가 접근할 브로커 주소
    depends_on:
      - redpanda
